"""SigMF interchange (design document 5.1, 8.3).

write_sigmf() writes ORI's format: cf32_le interleaved I/Q, core:sample_rate, the
`ori:design` block with the same keys as ORI's eve_tx_sigmf.py, one annotation per symbol,
plus a `dses:schedule` block that embeds the schedule dictionary. read_sigmf() accepts
ORI's files as produced by eve_tx_sigmf.py (and ours): returns the IQ, the metadata, the
EveParams implied by ori:design, and the symbols, so a file can be played through the
DSES transmit chain unchanged (export/import only; DSES transmits by streaming).
"""
from __future__ import annotations

import datetime as _dt
import hashlib
import json
from dataclasses import dataclass, replace
from pathlib import Path
from typing import Dict, List, Optional, Sequence, Union

import numpy as np

from . import __version__
from .params import EveParams

GENPOLY_TEXT = ("BCH(127,106) t=3 narrow-sense systematic; genpoly "
                "x^21+x^18+x^17+x^15+x^14+x^12+x^11+x^8+x^7+x^6+x^5+x+1")


def _paths(base: Union[str, Path]):
    base = str(base)
    for suf in (".sigmf-data", ".sigmf-meta"):
        if base.endswith(suf):
            base = base[: -len(suf)]
    return Path(base + ".sigmf-data"), Path(base + ".sigmf-meta")


def write_sigmf(iq: np.ndarray, fs: float, base: Union[str, Path], params: EveParams,
                symbols: Sequence[int], rf_freq_hz: float, text: str = "",
                freq_offset_hz: Optional[float] = None, t_sym_s: Optional[float] = None,
                schedule: Optional[Dict] = None, datetime_utc: Optional[str] = None,
                description: str = "") -> Dict:
    """Write base.sigmf-data / base.sigmf-meta. freq_offset_hz defaults to params.f_if;
    t_sym_s to params.t_sym (the annotation grid uses round(t_sym * fs) samples/symbol
    like ORI)."""
    data_path, meta_path = _paths(base)
    f_top = (params.f_if if freq_offset_hz is None else float(freq_offset_hz)) + params.bandwidth
    if f_top > fs / 2:
        raise ValueError(f"comb reaches {f_top:.0f} Hz above the dial but the file rate {fs:.0f} S/s "
                         "only holds +/- fs/2: write baseband (freq_offset_hz=0) or use a higher rate")
    x = np.asarray(iq).astype(np.complex64)
    inter = np.empty(x.size * 2, dtype=np.float32)
    inter[0::2] = x.real
    inter[1::2] = x.imag
    inter.tofile(data_path)
    sha = hashlib.sha512(data_path.read_bytes()).hexdigest()
    f_off = params.f_if if freq_offset_hz is None else float(freq_offset_hz)
    t_sym = params.t_sym if t_sym_s is None else float(t_sym_s)
    nsps = int(round(t_sym * fs))
    ann = []
    for m, d in enumerate(symbols):
        f0 = d * params.spacing + f_off
        ann.append({"core:sample_start": m * nsps, "core:sample_count": nsps,
                    "core:freq_lower_edge": rf_freq_hz + f0 - params.r_bw,
                    "core:freq_upper_edge": rf_freq_hz + f0 + params.r_bw,
                    "core:label": "sym %d  d=%d  f=%.2f Hz" % (m, d, f0)})
    meta = {
        "global": {
            "core:datatype": "cf32_le", "core:sample_rate": float(fs), "core:version": "1.0.0",
            "core:sha512": sha,
            "core:author": "Design: Pete Wyckoff KA3WCA (ORI). Generated by DSES eve.sigmf_io.",
            "core:description": description or ("EVE M-ary(4096) orthogonal FSK, BCH(127,106), 11 symbols. "
                                                f"Venus Bounce Transmitter Spiral #2. DSES Variant {params.variant}."),
            "core:recorder": f"dses-eve {__version__}",
            "ori:design": {
                "M": params.m, "bits_per_symbol": params.bits_per_symbol, "n_symbols": params.n_sym,
                "R_bw_hz": params.r_bw, "tone_spacing_hz": params.spacing,
                "t_sym_s": t_sym, "t_sym_design_s": params.t_sym,
                "bch": GENPOLY_TEXT, "crc": "CRC-16-CCITT poly 0x1021 init 0xFFFF over 90 msg bits",
                "payload_text": text, "symbols_d": [int(s) for s in symbols],
                "freq_offset_hz": f_off, "nco": "s_n = exp(i*2*pi*d*(2*R_bw)*n/Fs)  (Pete's equation)",
                "n_frames": params.n_frames, "n_fft": params.n_fft, "variant": params.variant,
                "bit_order": params.bit_order, "phase": "continuous",
            },
        },
        "captures": [{"core:sample_start": 0, "core:frequency": float(rf_freq_hz),
                      "core:datetime": datetime_utc or _dt.datetime.now(_dt.timezone.utc).isoformat()}],
        "annotations": ann,
    }
    if schedule is not None:
        meta["global"]["dses:schedule"] = schedule
    meta_path.write_text(json.dumps(meta, indent=2), encoding="utf-8")
    return meta


@dataclass
class SigmfRecording:
    iq: np.ndarray
    fs: float
    rf_freq_hz: float
    meta: Dict
    params: Optional[EveParams]
    symbols: List[int]
    freq_offset_hz: float
    t_sym_s: Optional[float]
    text: str
    schedule: Optional[Dict]

    @property
    def data_valid(self) -> bool:
        return bool(self.meta.get("_sha_ok", True))


def read_sigmf(base: Union[str, Path], verify_sha: bool = True, mmap: bool = False) -> SigmfRecording:
    data_path, meta_path = _paths(base)
    meta = json.loads(meta_path.read_text(encoding="utf-8"))
    g = meta["global"]
    if g.get("core:datatype") != "cf32_le":
        raise ValueError(f"unsupported datatype {g.get('core:datatype')}")
    raw = np.memmap(data_path, dtype=np.float32, mode="r") if mmap else np.fromfile(data_path, dtype=np.float32)
    iq = raw[0::2] + 1j * raw[1::2]
    iq = iq.astype(np.complex64)
    if verify_sha and g.get("core:sha512"):
        meta["_sha_ok"] = hashlib.sha512(data_path.read_bytes()).hexdigest() == g["core:sha512"]
    fs = float(g["core:sample_rate"])
    caps = meta.get("captures") or [{}]
    rf = float(caps[0].get("core:frequency", 0.0))
    d = g.get("ori:design", {})
    params = None
    if d:
        params = params_from_ori_design(d)
    return SigmfRecording(iq, fs, rf, meta, params, [int(s) for s in d.get("symbols_d", [])],
                          float(d.get("freq_offset_hz", 0.0)), d.get("t_sym_s"),
                          d.get("payload_text", ""), g.get("dses:schedule"))


def params_from_ori_design(d: Dict) -> EveParams:
    """EveParams implied by an ori:design block. ORI's own files carry R_bw, spacing, M,
    n_symbols and t_sym; frames per symbol follow from t_sym * R_bw unless the block
    (a DSES file) says n_frames."""
    p = EveParams.named(d.get("variant", "A")) if "variant" in d else EveParams.variant_a()
    kw = {}
    if "R_bw_hz" in d:
        kw["r_bw"] = float(d["R_bw_hz"])
    if "M" in d:
        kw["m"] = int(d["M"])
    if "n_symbols" in d:
        kw["n_sym"] = int(d["n_symbols"])
    if "n_frames" in d:
        kw["n_frames"] = int(d["n_frames"])
    elif "t_sym_s" in d and "R_bw_hz" in d:
        kw["n_frames"] = int(round(float(d["t_sym_s"]) * float(d["R_bw_hz"])))
    if "n_fft" in d:
        kw["n_fft"] = int(d["n_fft"])
    if "freq_offset_hz" in d:
        kw["f_if"] = float(d["freq_offset_hz"])
    if "bit_order" in d:
        kw["bit_order"] = str(d["bit_order"])
    if "tone_spacing_hz" in d and "R_bw_hz" in d:
        step = float(d["tone_spacing_hz"]) / float(d["R_bw_hz"])
        kw["tone_bin_step"] = int(round(step))
    return replace(p, **kw)


def symbol_tones_in_file(rec: SigmfRecording) -> List[float]:
    """For a cross-check of an imported file: the strongest frequency (Hz) in each
    annotated symbol span, from an FFT with bin width R_bw at the file's rate."""
    p = rec.params
    nfft = int(round(rec.fs / p.r_bw))
    out = []
    for a in rec.meta.get("annotations", []):
        s0, n = int(a["core:sample_start"]), int(a["core:sample_count"])
        seg = rec.iq[s0:s0 + min(n, nfft)]
        if seg.size < nfft:
            seg = np.concatenate([seg, np.zeros(nfft - seg.size, dtype=seg.dtype)])
        X = np.abs(np.fft.fft(seg))
        out.append(float(np.argmax(X) * rec.fs / nfft))
    return out
